repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-toml
      - id: check-json
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: check-shebang-scripts-are-executable
        files: \.sh$

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt
        args: ["-i", "2", "-ci", "-bn", "-sr"]

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
        name: Check Rust code
        description: Check the package for errors.
        args: []
      - id: clippy
        name: Lint Rust code
        description: Lint the package for style issues.
        args: [--all-targets, --all-features, --, -D, warnings]
      - id: fmt
        name: Format Rust code
        description: Format files with rustfmt.
