[package]
name = "qstorage"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow2 = "0.18"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3"
