[package]
name = "repl"
version = "0.1.0"
edition = "2024"

[dependencies]
rustyline = "10"
qparser = { path = "../qparser" }
qstorage = { path = "../qstorage" }
arrow2 = { version = "0.18", features = ["io_ipc"] }
bumpalo = "3.9"